config/routes.rb
# encoding: utf-8

Volunteer::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
  
  root to: 'home#index'

  resources :tasks do
    member do
      get :apply
      get 'assign/:user_id' => 'tasks#assign', as: 'assign_user'
      
      Task::ROLES.each do |role|
        delete "kick_#{role}/:user_id" => "tasks#kick_#{role}", as: "kick_#{role}"
      end

      put 'state/:state' => 'tasks#change_state', as: :change_state
      put :feedback
    end

    resources :comments, only: [:new, :create, :destroy]
  end

  resources :organizations do
    member do
      put :invite_user

      Organization::ROLES.each do |role|
        delete "kick_#{role}/:user_id" => "organizations#kick_#{role}", as: "kick_#{role}"
      end
    end

    resources :comments, only: [:new, :create, :destroy]
    resources :tasks, only: [:index]
  end

  resources :task_types, only: [] do
    put 'prefer' => 'preferences#prefer'
    put 'unprefer' => 'preferences#unprefer'
  end

  resources :prize_types, only: [] do
    put 'prefer' => 'preferences#prefer'
    put 'unprefer' => 'preferences#unprefer'
  end
  
  resources :users do
    member do
      put :ignore
      put :unignore
    end

    resources :comments, only: [:index, :new, :create, :destroy]
    resources :tasks,    only: :index
  end

  resources :pages, only: :show

  resources :messages, except: [:index, :show]

  get 'dialogs' => 'messages#dialogs',          as: :dialogs
  get 'dialogs/:dialog_id' => 'messages#index', as: :dialog

  post 'messages' => 'messages#create', as: :messages
end

app/models/task.rb
# encoding: utf-8

class Task < ActiveRecord::Base
  ROLES = [:applicant, :volunteer]
  STATES = { :reopen => { :value => 1, :state => :opened },
               :perform => { :value => 2, :state => :in_progress },
               :close => { :value => 3, :state => :closed }
              }
  resourcify
  paginates_per 6
  belongs_to :task_type
  belongs_to :owner,       class_name: 'User'
  belongs_to :organization

  has_many :task_prizes, dependent: :delete_all
  has_many :prize_types, through: :task_prizes

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :feedbacks
  has_many :events, as: :target, dependent: :delete_all

  # FILE UPLOAD #########

  mount_uploader :image, TaskImageUploader
  mount_uploader :file,  TaskFileUploader

  attr_accessible :title, :problem, :task_prizes, :deadline,
                  :task_type_id, :image, :file, :organization_id

  attr_accessor :user_id, :value, :body

  # VALIDATIONS #########

  validates :task_type, :organization, associated: true
  validates :task_type, presence: true
  validates :title,     presence: true, length: { in: 2..50 }
  validates :problem,   presence: true, length: { in: 10..300 }
  validates :deadline,  timeliness: { after: lambda{ Date.current + 1.day},
                                      type: :date, allow_blank: true, on: :create}

  validate :check_representative

  def check_representative
    if self.organization_id and !owner.all_organizations.include?(self.organization)
      errors.add(:organization, 'Необходимы права представителя!')
    end
  end

  scope :published, where('tasks.state < 4')
  scope :active, where('tasks.state < 3')
  scope :state, lambda {|st| where(:state => st)}

  scope :with_prize_type_id,    lambda { |tid| joins("right join (#{ TaskPrize.with_prize_type_id(tid).to_sql }) A on A.task_id = tasks.id") }
  scope :without_prize_type_id, lambda { |tid| joins("right join (#{ TaskPrize.without_prize_type_id(tid).to_sql }) A on A.task_id = tasks.id") }

  scope :free, where(is_free: true)
  scope :paid, where(is_free: false)
  scope :recent, order('created_at DESC')
  
  before_save :recalculate_paid
  after_create -> { make_task_event("created") }
  after_update -> { make_task_event("updated") unless self.state_changed? }

  # STATES #########

  state_machine :initial => :unpublished do
    state :opened,      value: 1
    state :in_progress, value: 2
    state :closed,      value: 3
    state :unpublished, value: 4
    state :deleted, value: 5

    event :reopen do
      transition all - [:opened, :unpublished, :deleted] => :opened
    end

    event :perform do
      transition :opened => :in_progress
    end

    event :close do
      transition all - [:closed, :unpublished, :deleted] => :closed
    end

    event :publish do
      transition :unpublished => :opened
    end

    event :delete_task do
      transition any => :deleted
    end

    after_transition any - [:unpublished, :deleted] => :closed do |task, trans|
      task.make_task_event("closed")
    end

    after_transition any - [:deleted] => :opened do |task, trans|
      task.make_task_event("opened")
    end

  end

  # INDEXING #########

  define_index do
    indexes :title
    indexes :problem

    has :state,        as: :state
    has :task_type_id, as: :types, type: :integer
    has :is_free,  type: :boolean

    has task_prizes.prize_type_id, as: :prizes
  end

  def self.search(params)
    page_num = (params[:page] || 1).to_i
    query = params[:text]

    filters = [:types, :prizes, :state].inject({}) do |a,o|
      a[o] = params[o] if params[o].present?; a
    end
    if query or filters.any?
      filters[:is_free] = (params[:is_free] == 't') if params[:is_free].present?
      super(query, with: filters, without: { state: [4, 5] }, page: page_num, per_page: 4, match_mode: :any)
    else
      result = page(page_num).per(4)

      if params[:is_free].present?
        result = (params[:is_free] == 't' ? result.free : result.paid) 
      end
      
      result
    end
  end

  def task_prizes=(params)
    task_prizes.delete_all
    params.reject { |p| p['prize_type_id'].nil? }.each { |params| task_prizes << TaskPrize.new(params) }
  end

  def user_role(user)
    role = self.roles.joins(:users).where('users.id' => user.id).first
    return role || false
  end

  def recalculate_paid
    self.is_free = self.task_prizes.all?{|type| type.prize_type.is_free }
    true
  end

  def users
    User.includes(:roles).where('roles.resource_type' => 'Task', 'roles.resource_id' => id)
  end

  ROLES.each do |role|
    define_method role.to_s.pluralize do
      users.where('roles.name' => role)
    end
  end

  def make_task_event(msg)
    TaskEvent.create(actor: self, user: owner, target: self, message: msg)
  end
end

app/models/task_type.rb
# encoding: utf-8

class TaskType < ActiveRecord::Base

  has_many :tasks

  mount_uploader :image, TaskTypeImageUploader

  attr_accessible :name, :image

  validates :name,  presence: true, length: { in: 3..100 }, uniqueness: { with: true, case_sensitive: false }
  
end

app/controllers/tasks_controller.rb
# encoding: utf-8

class TasksController <  InheritedResources::Base
  respond_to :js, only: [:apply, :assign]

  before_filter :authenticate_user!, except: [:index, :show]

  load_and_authorize_resource

  #belongs_to :user, :organization, :optional => true
  has_scope :page, :default => 1

  def current_search_path
    @current_search_path ||= tasks_path
  end

  def index
    authorize! :index, Task

    @tasks = Task.includes(:comments).published.active.recent.search(params)
  end

  def show
    @users = @task.users.group_by{|u|u.roles.first.name}.sort{|a,b| b<=>a}
    @events = @task.events.order("created_at ASC")
  end

  def new
    @organizations = current_user.all_organizations
    new!
  end

  def edit
    @organizations = current_user.all_organizations
    edit!
  end

  def create # WTF?
    authorize! :build, @task
    create!
  end

  def assign
    user = User.find(params[:user_id])
    
    if @task.user_role(user) && @task.user_role(user).name == 'volunteer'
      flash[:warning] = t("user.already_assigned", user: user.full_name)
    else
      user.add_role :volunteer, @task
      user.revoke :applicant, @task
      @task.fire_state_event :perform if @task.opened?
      flash[:notice] = t("user.assigned", user: user.full_name)
    end

    respond_with(@task) do |format|
      format.html {redirect_to(@task)}
    end
  end

  def apply
    if @task.user_role(current_user)
      flash[:warning] = t('user.already_aplied')
    else
      current_user.add_role :applicant, @task
    end

    respond_with(@task) do |format|
      format.html {redirect_to(@task)}
    end
  end

  Task::ROLES.each do |role|
    define_method "kick_#{role}" do
      user = User.find(params[:user_id])
      user_role = user.remove_role(role, @task)

      flash[:notice] = t("user.removed", 
        user: user.full_name,
        role: t("role.of_#{role.to_s.pluralize}")
      ) if user_role.present?

      redirect_to @task
    end
  end

  def feedback
    feedback = @task.feedbacks.create(params[:task])
    
    if feedback.save
      flash[:notice] = "Спасибо за Ваш отзыв!"
    else
      flash[:error] = feedback.errors.map { |attr, msg| msg }.join(' ')
    end

    redirect_to @task
  end

  def change_state
    begin
      @task.fire_state_event params[:state]
    rescue IndexError => e
      flash[:error] = "#{e.message}"
    else
      if @task.errors.any?
        flash[:error] = @task.errors.full_messages.join('\n')
      end
    end

    redirect_to @task
  end

  def build_resource
    @task ||= end_of_association_chain.new(params[:task])
    @task.owner = current_user
    @task
  end
  
end

app/helpers/tasks_helper.rb
# encoding: utf-8

module TasksHelper
  
  def task_apply_button(task)
    if task.user_role(current_user)
      content_tag :span, :id => "task-#{task.id}",
                  :class => "btn btn-small btn-warning disabled" do
        content_tag(:i, :class => 'icon-ok')
        'Вы ' + t("role.#{task.user_role(current_user).name}")
      end
    else
      link_to apply_task_path(task),
              :id     => "task-#{task.id}",
              :class  => "btn btn-small btn-warning" do
        content_tag(:i, :class => 'icon-ok')
        'Хочу попробовать'
      end
    end
  end

  def feedback(user)
    feedback = user.feedbacks.for_task(@task.id).first
    if feedback.blank? && can?(:feedback, @task)
      render 'feedback_form', :user => user
    else
      render 'users/user_rating', :user => user if feedback.present?
    end
  end

  def kick_role_task_path(role, user)
    method("kick_#{role}_task_path").call(:user_id => user.id)
  end

  def state_switcher
    html = Task::STATES.map do |act,val|
      if @task.method("#{val[:state]}?").call
        task_state
      else
        link_to(
          t("task.state.#{val[:state].to_s}"), change_state_task_path(@task, act),
          :class => "btn btn-mini #{@task.state == val[:value] ? 'active' : ''}", 
          :type => "button",
          :method => :put
        )
      end
    end.join.html_safe
  end

  def task_state
    state = Task::STATES.find{ |act, st| 
      st[:value] == @task.state 
    }[1][:state].to_s

    content_tag(:span, t("task.state.#{state}"), 
      :class => "btn btn-mini active #{state}"
    )
  end

  def task_state_name(state)
    case state
    when 1
      'opened'
    when 2
      'in_progress'
    when 3
      'closed'
    when 4
      'unpublished'
    end
  end

  def empty_tasks_table(tasks)
    html = []
    [1,2,3,4].each do |state|
      if !tasks.select{|s,t| s == state}.present?
        html << content_tag(:div, 
          t("none.task.state.#{task_state_name(state)}"),
          :class => "tab-pane #{state == 1 ? 'active': ''}", 
          :id => task_state_name(state)
        )
      end
    end
    html.join.html_safe
  end

  def tasks_page_title(params)
    if params[:is_free].present?
      case params[:is_free]
      when 't'
        'Бесплатные задачи'
      when 'f'
        'Платные задачи'
      end
    else
      'Задачи'
    end
  end

end

app/views/tasks/_events.haml
.events
  %h4 История задачи:

  - if @events.any?
    %ul.comment-list= render @events

  - if (can? :create, Comment) && (can? :comment, @task)
    .add-comment= render partial: 'comments/form'

app/views/tasks/_feedback_form.html.haml
.applicant-rate.pull-left
  = link_to 'оценить', "#rate-applicant-#{user.id}",:class => "btn btn-success btn-mini btn-block",:data => {:toggle => 'modal'}, :role => "button"
  .modal.hide.fade{:id => "rate-applicant-#{user.id}"}
    - @task.feedbacks.build
    = simple_form_for @task, :url => feedback_task_path(@task) do |f|
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
        %h3
          Оставьте ваш отзыв о пользователе
          %span{:style => "font-size:12px; color: #bbbbbb"}
            
      .modal-body.feedback-form
        .control-group
          = f.hidden_field :user_id, :value => user.id
          = f.text_area :body, col: 80, rows: 7
      .modal-footer
        = f.button :submit, 'Отправить'

app/views/tasks/_filters.html.haml
= form_tag tasks_path, method: :get, class: 'form-search pull-right' do
  %label.filter-text Сортировать:
  
  = select_prize_types(params[:prizes])
  = select_task_types(params[:types])
  = select_task_state(params[:state])

  %button{:name => nil, :type => 'submit', :class => 'btn btn-mini', :title => 'Применить фильтр'}
    %i.icon-refresh

app/views/tasks/_form.html.haml
= simple_form_for @task, html: { class: '' } do |f|
  
  .span12
    - if @task.errors.any?
      #error_explanation.well.alert-error
        %h3
          = t('errors.messages.not_saved', :count => resource.errors.count)
        %ul
          - @task.errors.full_messages.each do |msg|
            - if @task.errors[:file].present?
              %li= t('errors.messages.extension_list',  |
                     extensions: @task.file.white_list) |
            - else
              %li= msg

  .span8
    .control-group
      %label.control-label{:for => :organization} Ваша организация
      .controls
        = f.input :organization_id, :label => false, :collection => @organizations

    .control-group
      %label.control-label.pull-left{:for => :title} 
        %abbr{:title => 'Обязательное поле'} *
        Краткое описание задачи
      %a.west{:href => "#", :title => "Заголовок задачи должен быть кратким и емким. Уложитесь в 50 символов. Хороший пример заголовка:“Фонду А нужно создать сайт для ...”"} 
        %i.icon-question-sign      
      .controls
        = f.text_field :title, :class => "span7"

      %p.charsLeft
        Осталось знаков:
        %span#task_title_charsLeft         

    .control-group
      %label.control-label.pull-left{:for => :problem} 
        %abbr{:title => 'Обязательное поле'} *
        Дополнительная информация
      %a.west{:href => "#", :title => "Опишите проблему, которая перед вами стоит. “Готовится [мероприятие], посвященное [тема]."}
        %i.icon-question-sign
      .controls
        = f.text_area :problem, col: 40, rows: 7, :class => "span7"
 

      %p.charsLeft
        Осталось знаков:
        %span#charsLeft

    .control-group
      %label.control-label{:for => :image} Прикрепить картинку
      .controls
        = f.file_field :image
    .control-group
      %label.control-label{:for => :file} Приложить файл
      .controls
        = f.file_field :file

  .span-tasksidebar
    .control-group
      %label.control-label.pull-left{:for => :task_type_id} Тип задачи
      %a.west{:href => "#", :title => "Мы подобрали для вас наиболее часто встречающиеся типы IT-задач. Выберите подходящий тип под вашу задачу."}
        %i.icon-question-sign       
      .controls
        = f.select :task_type_id, options_for_select( TaskType.all.map { |type| [type.name, type.id] }, @task.task_type_id )

    .control-group
      %label.control-label{:for => :deadline} Крайний срок

    .control-group    
      #dp3.input-append.date{"data-date" => "", "data-date-format" => "dd-mm-yyyy"}
        = f.text_field :deadline, value: @task.deadline.try(:strftime, "%d-%m-%Y"), class: :span2, size: 16
        %span.add-on
          %i.icon-th

    = render partial: 'tasks/prize_types'

  .span7.t-right
    = link_to 'Отмена', tasks_path, class: 'btn'
    = f.button :submit, 'Отправить', class: 'btn btn-success'

app/views/tasks/_free_tasks.html.haml
.span4.task_well
  %h1 Бесплатные задачи
  
  - @free_tasks.each do |task|

    .row.taskbox
      .span1
        = link_to task.owner do
          = image_tag(task.owner.avatar.url(:thumb), :data => {"original-title" => task.owner.full_name}, :rel => "tooltip", :class => 'rounded')
      
      .span3
        %p
          = link_to task.title, task
          %br
          - task_prize = task.task_prizes.includes(:prize_type).first
          = render 'tasks/task_prize', :task_prize => task_prize

  = link_to "Все задачи", tasks_path(is_free: :t), :class => "btn btn-small btn-warning pull-right"

app/views/tasks/_prize_types.html.haml
.control-group
  %label.control-label.pull-left{:for => :prizes} Награда
  %a.west{:href => "#", :title => "Награды – ключевая вещь для успешности вашей задачи. Обещайте только то, что вы сможете сделать. Если вы не сможете сделать то, что обещаете, тогда на вас обидятся."} 
    %i.icon-question-sign 
  .control-group
    %label.checkbox.clear
      %input#check_all{:type => "checkbox"} Выбрать все награды

  - task_prizes = @task.task_prizes.reduce({}) { |a,t| a[t.prize_type_id] = t; a }

  - PrizeType.all.each do |prize_type, index|
    - task_prize = task_prizes[prize_type.id]

    %label.checkbox.clear
      = check_box_tag "task[task_prizes][#{index}][prize_type_id]", prize_type.id, !task_prize.nil?, class: 'checked'
      %i.icon-gift
      = prize_type.name

    - unless prize_type.segregate
      = number_field_tag "task[task_prizes][#{index}][count]", task_prize.try(:count), class: 'input-append'
  

app/views/tasks/_task.html.haml
%article.task_well
  .row
    .span8      
      %h2
        %i.icon-link.pull-left
        = link_to task.title, task_path(task), :class => 'task-head-link'
      .task-tags
        %span.label.label-info.task-status= t("task.state.#{task.state_name}")       
        %span.label.label-info.task-type= task.task_type.name

      .task-description= task.problem
      .task-meta
        - if not task.unpublished?
          Опубликовал&nbsp;
          
          = link_to task.owner, :class => "link_with_img" do
            = image_tag(task.owner.avatar.url(:thumb), :data => {"original-title" => task.owner.full_name}, :rel => "tooltip", :class => 'rounded')
            %span.link_without_img
              = task.owner.full_name 

          - if task.organization
            по инициативе&nbsp;
            = link_to task.organization, :class => "link_with_img" do
              = image_tag(task.organization.logo.url(:thumb), :data => {"original-title" => task.organization.name}, :rel => "tooltip", :class => 'rounded')
              %span.link_without_img
                = task.organization.name

      .task-controls
        = task_apply_button(task) if can? :apply, task
        / WTF?
        / = task.owner_id
        / = current_user.id
        / = task.class.name
        / = can? :apply, task


        %a{:href => task_path(task), :class => "btn btn-small btn-inverse"}
          %i.icon-question-sign
          Уточнить детали
        
    .span-tasksidebar
      .task-sidebar-block-item
        - if can? :edit, task
          = link_to 'Редактировать', edit_task_path(task), :class => 'btn btn-mini btn-block'
        -# если не админ - показываем кнопку "Вступить"
        -# т.п. показывается либо кнопка Редактировать, либо кнопка Вступить
        
        / = link_to 'Вступить', "#", :class => 'btn btn-mini btn-block btn-warning'
      
      .task-sidebar-block-item
        - if task.deadline
          %i.icon-calendar
          =l task.deadline, format: t('date.formats.short')
      .task-sidebar-block-item
        %ul
          - task.task_prizes.includes(:prize_type).each do |task_prize|
            - if task_prize.prize_type
              %li
                %i.icon-gift
                = task_prize.prize_type.name
                = render partial: 'tasks/task_prize'
                - if !task_prize.prize_type.segregate and task_prize.count
                  (
                  = task_prize.count
                  )

      .task-sidebar-block-item
        %i.icon-comment
        Обсуждение (#{task.comments.length})
        - if can? :create, Comment
          = link_to 'Прокомментировать', task_path(task)+"#new_comment"

      .task-sidebar-block-item
        %i.icon-heart
        Поделиться
        = render 'shared/add_this', :task => task

app/views/tasks/_task_prize.html.haml
- if task_prize.present?
  - if task_prize.prize_type
    %i.icon-gift
    = task_prize.prize_type.name
    - if !task_prize.prize_type.segregate and task_prize.count
      (
      = task_prize.count
      )

app/views/tasks/_task_with_thumb.html.haml
- @recent_tasks.each_with_index do |task, i|
  .span4{:class => i == 0 ? '' : 'offset1'}
    %p 
      = image_tag(task.organization.logo_url(:thumb))
      = link_to task.organization.name, task.organization
    .task-thumb
      = image_tag(task.image_url)
    .taskbox
      %p        
        = link_to task.title, task

    %p.blockbox
      - task_prize = task.task_prizes.includes(:prize_type).first
      = render 'tasks/task_prize', :task_prize => task_prize
    %p.blockbox
      - if task.deadline
        %i.icon-calendar
        =l task.deadline, format: t('date.formats.short')
    = link_to apply_task_path(task), :id => "task-#{task.id}",    |
              :class => "btn btn-block pull-right btn-warning" do |
      я хочу помочь

app/views/tasks/_tasks_in_table.html.haml
%ul#tabs-task.nav.nav-pills
  %li.active
    %a{"data-toggle" => "pill", :href => "#opened"} открытые
  %li
    %a{"data-toggle" => "pill", :href => "#in_progress"} в работе
  %li    
    %a{"data-toggle" => "pill", :href => "#closed"} закрытые
  %li    
    %a{"data-toggle" => "pill", :href => "#unpublished"} неопубликованные
.tab-content
  = empty_tasks_table(@tasks)
  - @tasks.each_pair do |state, tasks|
    - if tasks.any?
      .tab-pane{:id => task_state_name(state), :class => state == 1 ? 'active' : ''}
        %table.table.table-striped
          %thead
            %tr
              %th #
              %th Задача
              %th Дедлайн
          %tbody
            - tasks.each do |t|
              %tr
                %td
                  = link_to t.id, t, :title => "Перейти к просмотру задачи"
                %td= t.title
                %td= t.deadline.to_s(:short) if t.deadline
                -if t.unpublished?
                  %td
                    = link_to 'Опубликовать', change_state_task_path(t, 'publish'), :method => :put
  %p.t-center
    = link_to 'Посмотреть все задачи', method("#{resource_class.to_s.downcase}_tasks_path").call(resource), :class => 'btn btn-mini btn-block'

app/views/tasks/edit.html.haml
- model_class = Task
%article.task_well
  .row
    .span12
      %h2 Изменить задачу
    = render :partial => "form"

app/views/tasks/index.html.haml
= content_for(:filters) do
  = render partial: 'tasks/filters'
= render 'layouts/breadcrumbs'
= render 'layouts/add_and_search_panel'


#content
  - if @tasks.present?
    = render @tasks
  - else
    .article.task_well
      .row
        .span8
          %h3 Ничего не найдено.
  
.pagination
  = link_to_next_page @tasks, 'Загрузить больше задач', remote: true, id: "load_more_link", class: "btn btn-block", "data-loading-text" => "Loading...", type: "button"

app/views/tasks/index.js.erb
// $('#content').html('<%= escape_javascript render(@tasks) %>');
// $('.pagination').html('<%= escape_javascript(paginate(@tasks, remote: true).to_s) %>');

$('#content').append("<%= escape_javascript(render partial: @tasks)%>");

<%- if not @tasks.last_page? %>

  <%- p = {remote: true, id: 'load_more_link', 
                      class: 'btn btn-block', 
         'data-loading-text' => 'Loading...', 
                       type: 'button'} %>

  <%- html = escape_javascript(link_to_next_page(@tasks, 'Загрузить больше задач', p)) %>

  $('#load_more_link').replaceWith("<%= html %>");
<% else %>
  $('#load_more_link').remove()
<% end %>

app/views/tasks/new.html.haml
= render 'layouts/breadcrumbs'
%article.task_well
  .row
    .span12
      %h2 Новая задача

    = render :partial => "form"