config/routes.rb
# encoding: utf-8

Volunteer::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
  
  root to: 'home#index'

  resources :tasks do
    member do
      get :apply
      get 'assign/:user_id' => 'tasks#assign', as: 'assign_user'
      
      Task::ROLES.each do |role|
        delete "kick_#{role}/:user_id" => "tasks#kick_#{role}", as: "kick_#{role}"
      end

      put 'state/:state' => 'tasks#change_state', as: :change_state
      put :feedback
    end

    resources :comments, only: [:new, :create, :destroy]
  end

  resources :organizations do
    member do
      put :invite_user

      Organization::ROLES.each do |role|
        delete "kick_#{role}/:user_id" => "organizations#kick_#{role}", as: "kick_#{role}"
      end
    end

    resources :comments, only: [:new, :create, :destroy]
    resources :tasks, only: [:index]
  end

  resources :task_types, only: [] do
    put 'prefer' => 'preferences#prefer'
    put 'unprefer' => 'preferences#unprefer'
  end

  resources :prize_types, only: [] do
    put 'prefer' => 'preferences#prefer'
    put 'unprefer' => 'preferences#unprefer'
  end
  
  resources :users do
    member do
      put :ignore
      put :unignore
    end

    resources :comments, only: [:index, :new, :create, :destroy]
    resources :tasks,    only: :index
  end

  resources :pages, only: :show

  resources :messages, except: [:index, :show]

  get 'dialogs' => 'messages#dialogs',          as: :dialogs
  get 'dialogs/:dialog_id' => 'messages#index', as: :dialog

  post 'messages' => 'messages#create', as: :messages
end

app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base
  rolify after_add: :create_role_event, after_remove: :remove_role_event
  
  acts_as_taggable

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :authentications, dependent: :destroy
  has_many :tasks, foreign_key: :owner_id
  has_many :organizations
  has_many :feedbacks

  has_many :comments, foreign_key: :owner_id, class_name: 'Comment'
  has_many :received_comments, as: :commentable, class_name: 'Comment', dependent: :destroy

  has_many :send_messages,   class_name: 'Message', foreign_key: :sender_id
  has_many :receiv_messages, class_name: 'Message', foreign_key: :receiver_id

  has_many :preferences, class_name: 'Preference'

  # FILE UPLOAD #########

  mount_uploader :avatar, AvatarUploader

  # ATTRIBUTES

  attr_accessor :org_presenter, :accept_terms, :subscribe
  
  attr_accessible :first_name, :last_name, :avatar, :avatar_cache, 
                  :remote_avatar_url, :email, :sex, :about, 
                  :password, :password_confirmation, :remember_me, :tag_list,
                  :website, :skype, :facebook, :twitter, :linkedin,
                  :organizations_attributes, :org_presenter, :city,
                  :accept_terms, :subscribe

  accepts_nested_attributes_for :organizations

  # VALIDATIONS #########

  validates :first_name, :last_name, presence: true, length: { in: 2..15 }
  validates :about, length: { maximum: 300 }
  validates :city, :email, :website, :skype, :facebook, :twitter, :linkedin, length: { maximum: 30 }

  scope :ratings, order('rating ASC')

  # INDEXING #########

  define_index do
    indexes :first_name
    indexes :last_name
    indexes :about
  end

  def self.search(params)
    page_num = (params[:page] || 1).to_i
    query = params[:text]

    if query = params[:text]
      super(query, page: page_num, per_page: 4)
    else
      page(page_num).per(4)
    end
  end

  ### OTHER ##########

  def org_presenter=(v)
    @org_presenter = (v == '1')
  end

  before_validation do
    organizations.clear if new_record? and !self.org_presenter
  end

  def prefer!(obj)
    preferences.find_or_create_by_preferenceble_id_and_preferenceble_type(obj.id, obj.class.name)
  end

  def prefered?(obj)
    preferences.prefer(obj).exists?
  end

  def unprefer!(obj)
    preferences.prefer(obj).delete_all
  end

  def ignored_users_ids
    self[:ignored_users_ids] ||= []
  end

  def ignored_users
    @ignored_users ||= User.find(ignored_users_ids)
  end

  def ignored?(user)
    user.nil? ? false : ignored_users_ids.include?(user.id)
  end

  def ignore!(user)
    transaction do
      u = User.find_by_id(self.id)
      u.lock!
      u.ignored_users_ids += [user.id]
      u.save!
    end
  end

  def unignore!(user)
    transaction do
      u = User.find_by_id(self.id)
      u.lock!
      u.ignored_users_ids -= [user.id]
      u.save!
    end
  end

  def feedback(task_id)
    feedbacks.for_task(task_id)
  end

  def potential_collocutor
    User.where('id not in (SELECT unnest(ignored_users_ids) FROM users WHERE id = ?)', self.id) - [self]
  end

  def self.build_user_wo_confirmation(omniauth)
    user = User.new first_name: omniauth['info']['first_name'],
                    last_name: omniauth['info']['last_name'],
                    email: omniauth['info']['email'],
                    remote_avatar_url: omniauth['info']['image'] || '',
                    password: Devise.friendly_token
    user.confirm!
    return user
  end

  def apply_omniauth(omniauth)
    authentications.build(provider: omniauth['provider'], uid: omniauth['uid'])
  end

  def password_required?
    ( !password.blank? || authentications.empty?) && super
  end

  def full_name
    [self.first_name, self.last_name].join(' ')
  end

  def to_s
    full_name
  end

  def admin?
    has_role? :admin
  end

  def owner?(organization)
    organization.user_id == self.id if organization.present?
  end

  def all_organizations
    (self.organizations.verified + self.representative_in).uniq
  end

  Organization::ROLES.each do |role|
    define_method role.to_s+'_in' do
      Organization.verified.with_role role, self
    end
  end

  private

  def create_role_event(role)
    RoleEvent.create actor: role,
                    target: role.resource,
                      user: self,
                    action: :add,
                   message: role.name
  end

  def remove_role_event(role)
    RoleEvent.create actor: role,
                    target: role.resource,
                      user: self,
                    action: :remove,
                   message: role.name
  end

end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < InheritedResources::Base
  
  before_filter :authenticate_user!
  
  load_and_authorize_resource
  
  has_scope :page, default: 1

  custom_actions resource: [:ignore, :unignore]

  def current_search_path
    @current_search_path ||= users_path
  end

  def index
    @users = User.search(params)
  end

  def show
    @tasks = @user.tasks.group_by(&:state)
  end

  def update
    successfully_updated = if want_to_change_password? or want_to_change_email?
      @user.update_with_password(params[:user])
    else
      @user.update_without_password(params[:user])
    end

    respond_to do |format|
      if successfully_updated
        # Sign in the user by passing validation in case his password changed
        sign_in @user, :bypass => true if want_to_change_password? and want_to_change_email?

        format.html { redirect_to @user}
        format.json { head :no_content } # 204 No Content
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def ignore
    current_user.ignore! @user
  end

  def unignore
    current_user.unignore! @user
  end

  private

  def want_to_change_password?
    @want_to_change_password ||= !params[:user][:password].empty? rescue false
  end

  def want_to_change_email?
    @want_to_change_email ||= params[:user][:email].present? and (@user.email != params[:user][:email]) rescue false
  end

end

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  .span12
    - if @user.errors.any?
      #error_explanation.well.alert-error
        %h3
          = t('errors.messages.not_saved', :count => resource.errors.count)
        %ul
          - @user.errors.each do |attr, err|
            %li Поле '#{t(attr)}' #{err}
  .form
    .span8
      .form-inline
        .controls.controls-row
          .span
            = f.input :first_name, :placeholder => "Введите имя", :required => true, :input_html => {:class => 'span4'} 
          .span
            = f.input :last_name, :placeholder => "Введите фамилию", :required => true, :input_html => {:class => 'span4'}

        .control-group
          .controls
            = f.input :city, :label => 'Город', :placeholder => 'Укажите город'
          %label.control-label{ :for => 'user_about' } Расскажите о себе
          .controls
            = f.input :about , :input_html => {:class => 'span8',:rows => "3"}, :label => false

        .control-group
          .controls                  
            %label.control-label{ :for => 'user_tag_list'}
              Профессиональные интересы и навыки
            = f.input :tag_list, :label => false, :placeholder => 'Введите теги через запятую', :input_html => {:class => 'span8', :rows => 3}
        .control-group
          .controls.controls-row

            %label.control-label{ :for => 'user_website'}
              Сайт
              = f.input :website, :input_html => {:class => 'span4'}, :label => false
            %label.control-label{ :for => 'user_skype'}
              Skype
              = f.input :skype, :input_html => {:class => 'span4'}, :label => false
            %label.control-label{ :for => 'user_facebook'}
              Facebook
              = f.input :facebook, :input_html => {:class => 'span4'}, :label => false
            %label.control-label{ :for => 'user_twitter'}
              Twitter
              = f.input :twitter, :input_html => {:class => 'span4'}, :label => false
            %label.control-label{ :for => 'user_linkedin'}
              Linkedin
              = f.input :linkedin, :input_html => {:class => 'span4'}, :label => false
        %legend Изменить данные учетной записи

        .controls.controls-row
          .control-group
            = f.input :email, :input_html => {:class => 'span4'}, :required => true#, :label => false
            %br   
            %label.control-label{ :for => 'user_password' }
              Пароль
              = f.input :password, :label => false, :input_html => { :autocomplete => 'off', :class => 'span4' }
            %br 
            %label.control-label{ :for => 'user_password_confirmation' }
              Подтвердите пароль
              = f.input :password_confirmation, :input_html => { :autocomplete => 'off',:class => 'span4'}, :label => false


      %p.t-right
        = link_to t('.cancel', default: t("helpers.links.cancel")), user_path, class: 'btn'
        = f.button :submit, 'Сохранить', :class => 'btn btn-success'
       
      .acc-delete.pull-right
        %p.pull-right
          %button#acc-delete-link.dash-link{:type => "button"} Удалить аккаунт
        %br
        #delete-acc.pull-right{:style => "display:none;"}
          %p Если вы удалите ваш аккаунт, то его больше не будет.
          %form
            %fieldset
              %label.checkbox
                %input{:type => "checkbox"}
                  Я хочу удалить аккаунт
              %br
                %button.btn.pull-right{:type => "submit"} Удалить


    .span-tasksidebar
      %p.t-center= image_tag(@user.avatar_url ? @user.avatar : 'default_avatar.png', :class => "rounded", :id => "change_img")    
      %p.t-center
        %small
          %i.icon-pencil
          %a.change-avatar{:href => "#"} Изменить аватар
          %abbr{:title => 'Обязательное поле'} *
          = f.file_field :avatar, :class => 'hide', :onchange => "upload_img(this);", :type => "file"
          = f.file_field :avatar_cache, :class => 'hide'

        
- content_for :javascript do
  :javascript
    $('.change-avatar').on('click', function(){
      $('#user_avatar').click();
      return false;
    });
    $('#acc-delete-link').click(function() {
        $('#delete-acc').toggle();
    });

    function upload_img(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#change_img').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

app/views/users/_preferences.html.haml
.well
  .row
    .span8
      %h3 Предпочтения:
      %p Выберите типы задач и наград, которые вам интересны
    .span4
      %h4 Награды
      %ul.prize_types.unstyled
        - PrizeType.all.each do |prize_type|
          %li
            %label
              = check_box_tag "prize_type_#{prize_type.id}", nil, current_user.prefered?(prize_type),   |
                                                                  class: 'prize_type_preference',       |
                                           'data-unprefer-url' => prize_type_unprefer_path(prize_type), |
                                               'data-prefer-url' => prize_type_prefer_path(prize_type)  |

              = prize_type.name
    .span4
      %h4 Задачи
      %ul.task_types.unstyled
        - TaskType.all.each do |task_type|
          %li
            %label          
              = check_box_tag "task_type_#{task_type.id}", nil, current_user.prefered?(task_type), |
                                                                class: 'task_type_preference',     |
                                        'data-unprefer-url' => task_type_unprefer_path(task_type), |
                                          'data-prefer-url' => task_type_prefer_path(task_type)    |

              = task_type.name

app/views/users/_top_users.html.haml
.span4.task_well
  %h1 Доска почета
  - @users.each do |user|
    .row.taskbox
      .span1
        = image_tag(user.avatar_url)
      .span3
        %p
          = link_to user.full_name, user
          %br Рейтинг пользователя: +#{user.rating}
  = link_to "Все пользователи", users_path, :class => "btn btn-small btn-warning pull-right"

app/views/users/_user_rating.html.haml
.applicant-rate.pull-left
  %span.btn.btn-mini.disabled.btn-primary.btn-block 
    Рейтинг:
    = user.feedbacks.count

app/views/users/edit.html.haml
%article.task_well
  .row
    .span12
      %h2 Редактировать профиль пользователя
    = render 'form'

app/views/users/ignore.js.erb
jQuery('.ignore_or_unignore_link_<%= @user.id %>').text('разблокировать').attr('href', '<%= unignore_user_path(@user) %>').removeClass('btn-warning').addClass('btn-success')

app/views/users/index.html.haml
= render 'layouts/add_and_search_panel'
= render 'layouts/breadcrumbs'

#content
  %article.task_well
    .row
      .span8
        %h2 Пользователи
        - @users.each do |user|
          .row.article-content-block
            .span2
              = image_tag(user.avatar_url)
            .span6
              %h2
                = link_to user.full_name, user, :title => "Перейти в профиль"
              %p= user.about if user.about
              %p 
                Рейтинг пользователя: +#{user.rating}

  .pagination
    = paginate @users

app/views/users/show.html.haml
= render 'layouts/breadcrumbs'

%article.task_well
  .row
    .span8 
      .row.article-content-block
        .span2
          = image_tag(@user.avatar_url ? @user.avatar : 'default_avatar.png', class: "rounded")           
        .span6
          %h2
            %span.first-name= @user.first_name
            %span.last-name= @user.last_name
          %p= @user.about
        - if @user.city
          .span4
            - if can? :update, @user
              Город:
              = inplace_editable_link_to @user, 'city'
            - else
              Город: #{@user.city}
      .row.article-content-block
        .span8
          %h3 Контакты и социальные сети:
        - %w[email website skype twitter facebook linkedin].each_slice(3) do |contacts|
          - contacts.each do |contact|
            .span5
              .row
                .span1= contact.camelize + ':'
                .span3
                  - if can? :update, @user
                    = inplace_editable_link_to @user, contact
                  - else 
                    = @user.send(contact)
      .row.article-content-block
        .span8
          %h3 
            Профессиональные интересы и навыки:
          %p
            - if can? :update, @user
              = inplace_editable_link_to @user, :tag_list, {class: ' tags'} do
                - @user.tag_list.each do |tag|
                  %span.label.label-info= tag
            - else
              - @user.tag_list.each do |tag|
                %span.label.label-info= tag

      - if current_user == @user
        = render partial: 'users/preferences'

      .row.article-content-block
        .span8
          %h3 Ваши задачи:
          = render 'tasks/tasks_in_table'

    .span-usersidebar.span3
      - if can?(:send_message, @user) && @user != current_user
        .task-sidebar-block-item
          = new_message_link @user, 'отправить сообщение'

      - if can? :manage, @user
        .task-sidebar-block-item
          = link_to 'Редактировать профиль', edit_user_path, class: 'btn btn-mini btn-block'

      - if can? :create, Task
        = content_for(:new_button) do
          .span2
            = link_to new_task_path, class: 'btn btn-success btn-mini btn-block' do
              %i.icon-plus-sign
              Новая задача

      = render 'organizations/new_button'
      = render partial: 'messages/box'

app/views/users/unignore.js.erb
jQuery('.ignore_or_unignore_link_<%= @user.id %>').text('заблокировать').attr('href', '<%= ignore_user_path(@user) %>').removeClass('btn-success').addClass('btn-warning')