config/routes.rb
# encoding: utf-8

Volunteer::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
  
  root to: 'home#index'

  resources :tasks do
    member do
      get :apply
      get 'assign/:user_id' => 'tasks#assign', as: 'assign_user'
      
      Task::ROLES.each do |role|
        delete "kick_#{role}/:user_id" => "tasks#kick_#{role}", as: "kick_#{role}"
      end

      put 'state/:state' => 'tasks#change_state', as: :change_state
      put :feedback
    end

    resources :comments, only: [:new, :create, :destroy]
  end

  resources :organizations do
    member do
      put :invite_user

      Organization::ROLES.each do |role|
        delete "kick_#{role}/:user_id" => "organizations#kick_#{role}", as: "kick_#{role}"
      end
    end

    resources :comments, only: [:new, :create, :destroy]
    resources :tasks, only: [:index]
  end

  resources :task_types, only: [] do
    put 'prefer' => 'preferences#prefer'
    put 'unprefer' => 'preferences#unprefer'
  end

  resources :prize_types, only: [] do
    put 'prefer' => 'preferences#prefer'
    put 'unprefer' => 'preferences#unprefer'
  end
  
  resources :users do
    member do
      put :ignore
      put :unignore
    end

    resources :comments, only: [:index, :new, :create, :destroy]
    resources :tasks,    only: :index
  end

  resources :pages, only: :show

  resources :messages, except: [:index, :show]

  get 'dialogs' => 'messages#dialogs',          as: :dialogs
  get 'dialogs/:dialog_id' => 'messages#index', as: :dialog

  post 'messages' => 'messages#create', as: :messages
end

app/models/organization.rb
# encoding: utf-8

class Organization < ActiveRecord::Base
  ROLES = [:representative, :member]
  extend FriendlyId
  resourcify
  acts_as_taggable
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :tasks,     dependent: :destroy
  has_many :feedbacks, dependent: :delete_all
  
  # FILE UPLOAD #########
  
  mount_uploader :logo, LogoUploader
  
  attr_accessible :name, :about, :address, :logo, :logo_cache,
                  :website, :email, :skype, :twitter,
                  :facebook, :linkedin, :tag_list

  alias :avatar :logo
  
  def full_name
    self.name
  end

  attr_accessor :user_email, :role

  # VALIDATIONS #########
  
  validates :address, presence: true, length: { in: 10..100 }
  validates :website, website: true
  validates :name,    presence: true, length: { in: 3..100 }, 
                    uniqueness: { with: true, case_sensitive: false }

  scope :verified, where(verified: true)

  # INDEXING #########

  define_index do
    indexes :name
    indexes :about
    indexes :website
    indexes :skype
    indexes :twitter
    indexes :facebook
    indexes :linkedin

    has :verified,  type: :boolean
    # has :tag_list
  end

  def self.search(params)
    page_num = (params[:page] || 1).to_i
    query = params[:text]

    filters = [:is_group].inject({}) do |a,o|
      a[o] = params[o] if params[o].present?; a
    end

    if query or filters.any?
      filters[:verified] = true
      super(query, with: filters, page: page_num, per_page: 4)
    else
      verified.page(page_num).per(4)
    end
  end

  def verify!
    self.verified = true
    save!
  end

  def unverify!
    self.verified = false
    save!
  end

  def users
    User.includes(:roles).where('roles.resource_type' => 'Organization', 'roles.resource_id' => id)
  end

  def representatives
    users.where('roles.name' => 'representative')
  end

  def members
    users.where('roles.name' => 'member')
  end

end

app/controllers/organizations_controller.rb
# encoding: utf-8

class OrganizationsController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource
  respond_to :html

  def current_search_path
    @current_search_path ||= organizations_path
  end

  def index
    @organizations = Organization.search(params)
  end

  def show
    page_not_found unless @organization.verified?
    @users = @organization.users
             .group_by{|u|u.roles.first.name}.sort{ |a,b| b <=> a }
    @tasks = @organization.tasks.group_by(&:state)
  end

  def create
    create! do |s,f|
      s.html { redirect_to organizations_path }
    end
  end

  def update
    update! do |format|
      format.html { redirect_to resource, notice:  'Updated' }
      format.json { head :no_content }

      format.html { render action: "edit" }
      format.json { render json: resource.errors, status: :unprocessable_entity }
    end
  end

  def invite_user
    if params[:organization][:user_email].present? && params[:organization][:role].present?
      user = User.find_by_email(params[:organization][:user_email])

      if user.nil?
        flash[:warning] = t('none.user.with_email', :email => params[:organization][:user_email])
      else
        role = user.add_role params[:organization][:role], @organization if Organization::ROLES.include? params[:organization][:role].to_sym
        flash[:notice] = t('org.user_added', :user => user.full_name, :role => t("role.as_#{role.name}"))
      end
    else
      flash[:error] = t('org.wrong_user')
    end
    redirect_to @organization
  end

  Organization::ROLES.each do |role|
    define_method "kick_#{role}" do
      user = User.find(params[:user_id])
      user_role = user.remove_role(role, @organization)

      flash[:notice] = t("user.removed", 
        :user => user.full_name,
        :role => t("role.of_#{role.to_s.pluralize}")
      ) if user_role.present?
      
      redirect_to @organization
    end
  end

  private
  def build_resource
    organization = params[:organization]
    @organization ||= end_of_association_chain.new(organization)
    @organization.user = current_user
    @organization.verified = false
    @organization
  end

end

app/helpers/organizations_helper.rb
# encoding: utf-8

module OrganizationsHelper

  def join_organization_button(organization)
    if current_user.has_any_role?({:name => :member, :resource => organization},
                                  {:name => :representative, :resource => organization})
      link_to 'Покинуть', "#", :class => 'btn btn-mini btn-block'
    else
      link_to 'Вступить', "#", :class => 'btn btn-mini btn-block btn-warning'
    end
  end

end

app/views/organizations/_filters.html.haml
= form_tag tasks_path, method: :get, class: 'form-search pull-right' do
  %label.filter-text Сортировать:
  
  = select_organization_types(params[:is_group])

  %button{:name => nil, :type => 'submit', :class => 'btn btn-mini', :title => 'Применить фильтр'}
    %i.icon-refresh

app/views/organizations/_form.html.haml
= simple_form_for(@organization) do |f|
  .span12
    - if @organization.errors.any?
      #error_explanation.well.alert-error
        %h3
          = t('errors.messages.not_saved', :count => resource.errors.count)
        %ul
          - @organization.errors.full_messages.each do |msg|
            %li= msg  
  
  %form
    .span8
      = f.input :name,     label: 'Название компании', input_html: {class: 'span6'}
      = f.input :address,  label: 'Адрес',    input_html: {class: 'span4'}
      = f.input :website,  label: 'Сайт',     input_html: {class: 'span4'}
      = f.input :email,    label: 'Email',    input_html: {class: 'span4'}
      = f.input :skype,    label: 'Skype',    input_html: {class: 'span4'}
      = f.input :twitter,  label: 'twitter',  input_html: {class: 'span4'}
      = f.input :facebook, label: 'facebook', input_html: {class: 'span4'}
      = f.input :linkedin, label: 'linkedin', input_html: {class: 'span4'}
      = f.input :about,    label: 'Расскажите чем занимается компания', input_html: {class: 'span6', rows: 3}
      = f.input :tag_list, label: 'Теги', placeholder: 'Введите теги через запятую', input_html: {class: 'span6', rows: 3}
      .span6.t-right
        / = link_to t('.cancel', default: t("helpers.links.cancel")), organizations_path, class: 'btn'
        / = f.file_field :logo,       class: "hide"
        / = f.file_field :logo_cache, class: "hide"

        = f.button :submit, 'Сохранить', class: 'btn btn-success'

    .span-tasksidebar
      %p.t-center= image_tag(@organization.logo.url, :class => "rounded", :id => "change_img")    
      %p.t-center
        %small
          %i.icon-pencil
          %a.change-logo{:href => "#"} Изменить аватар
          = f.file_field :logo, :class => 'hide', :onchange => "upload_img(this);", :type => "file"
          = f.file_field :logo_cache, :class => 'hide'

- content_for :javascript do
  :javascript
    $(function() {
      window.upload_img = function (input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
              $('#change_img').attr('src', e.target.result);
          }
          reader.readAsDataURL(input.files[0]);
        }
      }
    })

app/views/organizations/_invite_user.html.haml
%h3 
  Пригласить пользователей:
  .task-sidebar-block-item
    = simple_form_for @organization, :url => invite_user_organization_path(@organization) do |f|
      = f.input :user_email, :label => 'Адрес эл. почты'
      = f.input :role, :collection => Organization::ROLES.map{|r|[t("role.#{r}"), r]}, :label => 'Роль', :include_blank => false
      = f.button :submit, 'Пригласить'

app/views/organizations/_new_button.html.haml
= link_to new_organization_path, :class => 'btn btn-success btn-mini btn-block' do
  %i.icon-plus-sign
  Создать организацию

app/views/organizations/_registration.html.haml
.control-group
  = f.label "Вы представитель организации?", class: 'control-label'
  .controls
    = f.check_box :org_presenter, :tabindex => "8"

- f.object.organizations.build unless f.object.organizations.present?

= f.simple_fields_for :organizations do |org_form|
  %fieldset
    = org_form.input :name, placeholder: "Название вашей организации", label: 'Название организации', input_html: {class: 'span3', :tabindex => "9"}
    = org_form.input :address, label: 'Адрес', input_html: {:tabindex => "10"}

    .t-right
      = f.file_field :logo, class: "hide"
      = f.file_field :logo_cache, class: "hide"
    
    = org_form.input :website, placeholder: "http://site.ru", label: 'Сайт', input_html: {:tabindex => "11"}

    = org_form.input :about, as: :text, label: 'Расскажите, чем занимается организация', input_html: {class: 'span3', rows: 3, :tabindex => "12"}

app/views/organizations/_users.html.haml
.task-sidebar-block-item
  %ul.team-list
    - @users.each do |role, users|
      %li.team-role
        .rolet= t("role.#{role.pluralize}")
        %ul.user-list
          - users.each do |u|
            %li.user-list-item
              .list-item-img
                = image_tag(u.avatar_url(:thumb)) if u.avatar
              .list-item-user
                %span.user-name= u.full_name
                %span.user-control
                  %a{:href => "#"} Написать личное сообщение
              = link_to 'x', eval("kick_#{role}_organization_path(:user_id => u)"), :method => :delete, :confirm => 'Вы уверены?' if can? "kick_#{role}", @organization

app/views/organizations/edit.html.haml
%article.task_well
  .row
    .span12
      %h2 Изменить данные

    = render :partial => "form"

app/views/organizations/index.html.haml
= render 'layouts/breadcrumbs'
= content_for(:new_button) do
  .span2
    = render 'new_button'
= render 'layouts/add_and_search_panel'

= content_for(:filters) do
  = render partial: 'organizations/filters'

- @organizations.each do |organization|
  %article.task_well
    .row
      .span8 
        .row.article-content-block
          .span2
            = link_to image_tag(organization.logo, :class => "rounded", :alt => organization.name), organization, :title => "Go to organization profile"
          .span6
            %h2= organization.name
            %p= organization.about
            %p= link_to 'Подробнее', organization, :class => "btn btn-mini", :title => "Go to organization profile"

      .span-tasksidebar
        .task-sidebar-block-item
          = join_organization_button(organization)
        .task-sidebar-block-item
          %i.icon-user
          Участников 
          ="(#{organization.users.count})"

app/views/organizations/new.html.haml
= render 'layouts/breadcrumbs'
%article.task_well
  .row
    .span12
      %h2 Добавить новую организацию
    
    = render "form"

app/views/organizations/show.html.haml
= content_for(:new_button) do
  .span2
    = render 'new_button'
= render 'layouts/breadcrumbs'
= render 'layouts/add_and_search_panel'
%article.task_well
  .row
    .span8 
      .row.article-content-block
        .span2
          = image_tag(@organization.logo_url, :class => "rounded")
        .span6
          %h2= @organization.name
          %p= @organization.about

      .row.article-content-block
        .span8
          %h3 Контакты и социальные сети:
        - %w[email website skype twitter facebook linkedin].each_slice(3) do |contacts|
          - contacts.each do |contact|
            .span5
              .row
                .span1= contact.camelize + ':'
                .span3
                  - if can? :update, @organization
                    = inplace_editable_link_to @organization, contact
                  - else 
                    = @organization.send(contact)

      .row.article-content-block
        .span8
          %h3 
            Область деятельности организации:
          %p
            = inplace_editable_link_to @organization, :tag_list, {class: ' tags'} do
              - @organization.tag_list.each do |tag|
                %span.label.label-info= tag

      .row.article-content-block
        .span8
          %h3 Задачи:
          = render 'tasks/tasks_in_table'
    .span-tasksidebar
      - if can? :update, @organization
        .task-sidebar-block-item
          = link_to 'Edit', edit_organization_path(@organization), :class => 'btn btn-mini btn-block'
      = render 'users'
      - if can? :manage, @organization
        = render 'invite_user'