config/routes.rb
# encoding: utf-8

Volunteer::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
  
  root to: 'home#index'

  resources :tasks do
    member do
      get :apply
      get 'assign/:user_id' => 'tasks#assign', as: 'assign_user'
      
      Task::ROLES.each do |role|
        delete "kick_#{role}/:user_id" => "tasks#kick_#{role}", as: "kick_#{role}"
      end

      put 'state/:state' => 'tasks#change_state', as: :change_state
      put :feedback
    end

    resources :comments, only: [:new, :create, :destroy]
  end

  resources :organizations do
    member do
      put :invite_user

      Organization::ROLES.each do |role|
        delete "kick_#{role}/:user_id" => "organizations#kick_#{role}", as: "kick_#{role}"
      end
    end

    resources :comments, only: [:new, :create, :destroy]
    resources :tasks, only: [:index]
  end

  resources :task_types, only: [] do
    put 'prefer' => 'preferences#prefer'
    put 'unprefer' => 'preferences#unprefer'
  end

  resources :prize_types, only: [] do
    put 'prefer' => 'preferences#prefer'
    put 'unprefer' => 'preferences#unprefer'
  end
  
  resources :users do
    member do
      put :ignore
      put :unignore
    end

    resources :comments, only: [:index, :new, :create, :destroy]
    resources :tasks,    only: :index
  end

  resources :pages, only: :show

  resources :messages, except: [:index, :show]

  get 'dialogs' => 'messages#dialogs',          as: :dialogs
  get 'dialogs/:dialog_id' => 'messages#index', as: :dialog

  post 'messages' => 'messages#create', as: :messages
end

app/views/layouts/_add_and_search_panel.html.haml
= content_for(:search) do
  .container.m-bottom20
    .row
      = content_for(:new_button)
      .span5.pull-right
        = form_tag current_search_path, method: :get, class: 'form-search' do
          = text_field_tag :text, params[:text], placeholder: "Введите текст", :class => 'search-query'
          %button.pull-right{:name => :nil, :type => 'submit', :class => 'btn', :title => 'Найти'}
            %i.icon-search

app/views/layouts/_breadcrumbs.html.haml
= content_for(:breadcrumbs) do
  .breadcrumb 
    .span= render_navigation :renderer => :breadcrumbs,  :join_with => " / "
    .span8.pull-right= yield :filters

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .container.nav-collapse
        %ul.nav.top-panel
          - if user_signed_in?
            %li
              Привет, 
              %i.icon-user
              = link_to current_user.first_name, user_path(current_user), :title => "Перейти в профиль"
            %li
              %i.icon-envelope-alt
              = link_to "Сообщения", dialogs_path
            %li
              %i.icon-comments
              = link_to "Комментарии", user_comments_path(current_user)
            %li
              %i.icon-refresh
              = link_to "Участники", users_path
            %li
              %i.icon-tasks
              = link_to "Задачи", tasks_path
            -# %li= link_to "Tasks", tasks_path
            %li
              %i.icon-briefcase
              = link_to "Организации", organizations_path
        %ul.nav.pull-right
          - if user_signed_in?
            = link_to new_task_path, class: 'btn btn-success btn-mini pull-left m-top8' do
              %i.icon-plus-sign
              Новая задача
            %li.divider-vertical
            %li= link_to 'Выйти', destroy_user_session_path, :tabindex => "-1", :class => ""
          - else
            %li= link_to 'Зарегистрироваться', "#signup", :data => {:toggle => 'modal'}, :role => "button"

            %li.divider-vertical
            %li.dropdown
              = link_to 'Войти', "#signin", :data => {:toggle => 'modal'}, :role => "button"
%nav.navbar.navbar-transparent.navbar-static-top.devider-navbar
  .navbar-inner
    .container
      = link_to root_path, :class => 'brand' do
        %span.hide Volunteer

      .container.nav-collapse
        - if _routes_context.class != HomeController
          %ul.nav.pull-right
            %li= link_to "Волонтерам", page_path('it-volonteram')
            %li= link_to "Организациям", page_path('nko-i-obschestvennym-initsiativam')
            %li= link_to "Рейтинг", users_path

app/views/layouts/_modals.html.haml
#signup.modal.hide.fade.registration
  = render 'devise/registrations/new'
#signin.modal.hide.fade
  = render 'devise/sessions/new'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width,minimum-scale=0.5,maximum-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Volunteer"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico'
  %body.page-bg
    = render 'layouts/header'     

    .container
      = bootstrap_flash

    = yield :search

    %section.container
      = yield :breadcrumbs        
      = yield

    = render 'layouts/modals' unless current_user
    
    = javascript_include_tag "application"
    = content_for(:javascript)

app/views/layouts/home.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width,minimum-scale=0.5,maximum-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Volunteer"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico'
  %body.page-bg
    = render 'layouts/header'     

    .container
      = bootstrap_flash

    %section.container
       
      = yield

    = render 'layouts/modals' unless current_user

    = javascript_include_tag "application"
    = content_for(:javascript)

app/views/layouts/pages.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width,minimum-scale=0.5,maximum-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Volunteer"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico'
  %body.page-bg
    = render 'layouts/header'     

    .container
      = bootstrap_flash

    %section.container
      = yield :breadcrumbs
      .content
        %article.task_well
          .row
            .span12
              = yield

    = javascript_include_tag "application"
    = content_for(:javascript)